# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 13:07
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tweet_id', models.BigIntegerField(unique=True)),
                ('text', models.CharField(max_length=280)),
                ('truncated', models.BooleanField(default=False)),
                ('user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('filter_level', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('reply_count', models.PositiveIntegerField(blank=True, null=True)),
                ('retweet_count', models.PositiveIntegerField(blank=True, null=True)),
                ('favorite_count', models.PositiveIntegerField(blank=True, null=True)),
                ('in_reply_to_status_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('retweeted_status_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('entities', annoying.fields.JSONField(blank=True, deserializer=json.loads, null=True, serializer=annoying.fields.dumps)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('screen_name', models.CharField(max_length=50, verbose_name='Screen name')),
                ('location', models.CharField(max_length=300, verbose_name='Location')),
                ('url', models.URLField(max_length=300, null=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('protected', models.NullBooleanField(default=False, verbose_name='Protected')),
                ('verified', models.NullBooleanField(default=False, verbose_name='Verified')),
                ('followers_count', models.IntegerField(default=0, null=True)),
                ('friends_count', models.IntegerField(default=0, null=True)),
                ('listed_count', models.IntegerField(default=0, null=True)),
                ('favourites_count', models.IntegerField(default=0, null=True)),
                ('statuses_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField()),
                ('profile_banner_url', models.URLField(max_length=300, null=True)),
                ('profile_image_url_https', models.URLField(max_length=300, null=True)),
                ('default_profile', models.NullBooleanField(default=False, verbose_name='Default profile')),
                ('default_profile_image', models.NullBooleanField(default=False, verbose_name='Default profile image')),
                ('entities', annoying.fields.JSONField(blank=True, deserializer=json.loads, null=True, serializer=annoying.fields.dumps)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
